version: '3.7'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 10240000000
    ports:
      - 5432:5432

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.app:app --host 0.0.0.0 --port 5000 --loop uvloop --reload
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - jaeger
      - kibana
    volumes:
      - .:/www
    env_file:
      - ./.env

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686  # webui
      - 14268:14268  # http collector format=jaeger.thrift



  apm:
    image: elastic/apm-server:7.17.17
    depends_on:
      elasticsearch:
        condition: service_healthy
    cap_add: [ "CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID" ]
    cap_drop: [ "ALL" ]
    ports:
      - 8200:8200
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

  elasticsearch:
    image: elasticsearch:7.17.17
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    ports:
      - 9200:9200
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  kibana:
    image: kibana:7.17.17
    depends_on:
      apm:
        condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status



#  minio:
#    image: minio/minio
#    ports:
#      - 9000:9000
#      - 9001:9001
#      - 39271:39271
#    command: server /data --console-address :9001
#    volumes:
#      - ./.docker/minio:/data
#    environment:
#      - MINIO_ROOT_USER=minioadmin
#      - MINIO_ROOT_PASSWORD=minioadmin
