"""book-title

Revision ID: 9b2723faa27b
Revises: febcb52fe13c
Create Date: 2023-06-24 00:37:28.550803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2723faa27b'
down_revision = 'febcb52fe13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('title', sa.Text(), nullable=True))
    op.drop_constraint('fk_m2m_tag_book_on_tag', 'm2m_tag_book', type_='foreignkey')
    op.drop_constraint('fk_m2m_tag_book_on_book', 'm2m_tag_book', type_='foreignkey')
    op.create_foreign_key('fk_m2m_tag_book_on_tag', 'm2m_tag_book', 'tags', ['tag_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key('fk_m2m_tag_book_on_book', 'm2m_tag_book', 'books', ['book_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_m2m_tag_book_on_book', 'm2m_tag_book', schema='public', type_='foreignkey')
    op.drop_constraint('fk_m2m_tag_book_on_tag', 'm2m_tag_book', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_m2m_tag_book_on_book', 'm2m_tag_book', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_m2m_tag_book_on_tag', 'm2m_tag_book', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_column('books', 'title')
    # ### end Alembic commands ###
