"""books_init

Revision ID: cf94ec60e0d4
Revises: 
Create Date: 2023-06-20 16:25:37.235205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf94ec60e0d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('cover', sa.Text(), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books', schema='public')
    # ### end Alembic commands ###
