"""required_book_title

Revision ID: c072a35ffe96
Revises: 1b6be6e7b66e
Create Date: 2024-04-20 21:57:29.644162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c072a35ffe96'
down_revision = '1b6be6e7b66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('fk_m2m_tag_book_on_tag', 'm2m_tag_book', type_='foreignkey')
    op.drop_constraint('fk_m2m_tag_book_on_book', 'm2m_tag_book', type_='foreignkey')
    op.create_foreign_key('fk_m2m_tag_book_on_tag', 'm2m_tag_book', 'tags', ['tag_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key('fk_m2m_tag_book_on_book', 'm2m_tag_book', 'books', ['book_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('tags_parent_fk', 'tags', type_='foreignkey')
    op.create_foreign_key('tags_parent_fk', 'tags', 'tags', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_parent_fk', 'tags', schema='public', type_='foreignkey')
    op.create_foreign_key('tags_parent_fk', 'tags', 'tags', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_m2m_tag_book_on_book', 'm2m_tag_book', schema='public', type_='foreignkey')
    op.drop_constraint('fk_m2m_tag_book_on_tag', 'm2m_tag_book', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_m2m_tag_book_on_book', 'm2m_tag_book', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_m2m_tag_book_on_tag', 'm2m_tag_book', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.alter_column('books', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
