"""init_tree_tags

Revision ID: 1b6be6e7b66e
Revises: 9b2723faa27b
Create Date: 2024-04-19 13:54:05.920636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6be6e7b66e'
down_revision = '9b2723faa27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_m2m_tag_book_on_tag', 'm2m_tag_book', type_='foreignkey')
    op.drop_constraint('fk_m2m_tag_book_on_book', 'm2m_tag_book', type_='foreignkey')
    op.create_foreign_key('fk_m2m_tag_book_on_book', 'm2m_tag_book', 'books', ['book_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key('fk_m2m_tag_book_on_tag', 'm2m_tag_book', 'tags', ['tag_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('tags', sa.Column('parent_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('tags_parent_fk', 'tags', 'tags', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_parent_fk', 'tags', schema='public', type_='foreignkey')
    op.drop_column('tags', 'parent_id')
    op.drop_constraint('fk_m2m_tag_book_on_tag', 'm2m_tag_book', schema='public', type_='foreignkey')
    op.drop_constraint('fk_m2m_tag_book_on_book', 'm2m_tag_book', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_m2m_tag_book_on_book', 'm2m_tag_book', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_m2m_tag_book_on_tag', 'm2m_tag_book', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
