global:
  hostname: k8s.local

app:
  # version: git commit
  version: 0.0.1
  name: books
  image: sane4eg/books:latest
  ports:
    - name: http
      containerPort: 5000
      protocol: TCP
  env:
    - name: LOG_FORMATTER
      value: json
    - name: LOG_LEVEL
      value: INFO
    - name: ASYNCPG_DSN
      value: postgresql://postgres:postgres@postgres-books:5432/postgres
    - name: ELASTIC_APM_ENABLED
      value: "false"
