{
 "title": "Pod / RPS / Latency",
 "tags": [ "rps boilerplate" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Source", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(http_requests_latency_count,node)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(http_requests_latency_count,service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(http_requests_latency_count{service=~\"$service\"},pod)"
    }
   },
   {
    "name": "path",
    "label": "URL",
    "query": {
     "query": "label_values(http_requests_latency_count{service=~\"$service\"},path)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP 5xx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(http_requests_latency_count{status_code=~\"5.*\", service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(path) (rate(http_requests_latency_count{status_code=~\"5.*\", service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by() (rate(http_requests_latency_count{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(pod) (rate(http_requests_latency_count{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(path) (rate(http_requests_latency_count{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(http_requests_latency_bucket{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])))",
     "legendFormat": "100"
    },
    {
     "expr": "histogram_quantile(.98, sum by(le) (rate(http_requests_latency_bucket{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])))",
     "legendFormat": "98"
    },
    {
     "expr": "histogram_quantile(.95, sum by(le) (rate(http_requests_latency_bucket{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(.75, sum by(le) (rate(http_requests_latency_bucket{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])))",
     "legendFormat": "75"
    },
    {
     "expr": "histogram_quantile(.50, sum by(le) (rate(http_requests_latency_bucket{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])))",
     "legendFormat": "50"
    },
    {
     "expr": "histogram_quantile(.25, sum by(le) (rate(http_requests_latency_bucket{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])))",
     "legendFormat": "25"
    }
   ]
  },
  {
   "title": "Pod AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_latency_sum{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])) by (pod)\n     / sum(increase(http_requests_latency_count{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])) by (pod) < +Inf\n  or sum(increase(http_requests_latency_count{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_latency_sum {service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])) by (path)\n     / sum(increase(http_requests_latency_count{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])) by (path) < +Inf\n  or sum(increase(http_requests_latency_count{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])) by (path)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod 98%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(.98, sum by(le, pod) (rate(http_requests_latency_bucket{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL 98% percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(.98, sum by(le, path) (rate(http_requests_latency_bucket{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(http_requests_latency_count{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_requests_latency_count{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(.98, sum by(le, status_code) (rate(http_requests_latency_bucket{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(.98, sum by(le, method) (rate(http_requests_latency_bucket{service=~\"$service\", node=~\"$node\", pod=~\"$pod\", path=~\"$path\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}