{
 "title": "Cluster / RPS / Latency",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "HTTP 5xx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(service) (rate(http_requests_latency_count{status_code=~\"5.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(node) (rate(http_requests_latency_count{status_code=~\"5.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by() (rate(http_requests_latency_count[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(service) (rate(http_requests_latency_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(node) (rate(http_requests_latency_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(http_requests_latency_bucket[1m])))",
     "legendFormat": "100"
    },
    {
     "expr": "histogram_quantile(.98, sum by(le) (rate(http_requests_latency_bucket[1m])))",
     "legendFormat": "98"
    },
    {
     "expr": "histogram_quantile(.95, sum by(le) (rate(http_requests_latency_bucket[1m])))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(.75, sum by(le) (rate(http_requests_latency_bucket[1m])))",
     "legendFormat": "75"
    },
    {
     "expr": "histogram_quantile(.50, sum by(le) (rate(http_requests_latency_bucket[1m])))",
     "legendFormat": "50"
    },
    {
     "expr": "histogram_quantile(.25, sum by(le) (rate(http_requests_latency_bucket[1m])))",
     "legendFormat": "25"
    }
   ]
  },
  {
   "title": "Service AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_latency_sum [1m])) by (service)\n     / sum(increase(http_requests_latency_count[1m])) by (service) < +Inf\n  or sum(increase(http_requests_latency_count[1m])) by (service)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_latency_sum [1m])) by (node)\n     / sum(increase(http_requests_latency_count[1m])) by (node) < +Inf\n  or sum(increase(http_requests_latency_count[1m])) by (node)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service 98%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(.98, sum by(le, service) (rate(http_requests_latency_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node 98% percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(.98, sum by(le, node) (rate(http_requests_latency_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum by(status_code) (rate(http_requests_latency_count[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum by(method) (rate(http_requests_latency_count[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "histogram_quantile(.98, sum by(le, status_code) (rate(http_requests_latency_bucket[1m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "histogram_quantile(.98, sum by(le, method) (rate(http_requests_latency_bucket[1m])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}