apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.name }}-service-monitor-2
  namespace: prometheus
  labels:
    app.kubernetes.io/instance: {{ .Values.app.name }}
    app.kubernetes.io/name: {{ .Values.app.name }}
spec:
  endpoints:
    - interval: 1s
      path: /metrics
      port: http
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.app.name }}
      app.kubernetes.io/name: {{ .Values.app.name }}
